import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";

const poppins = Poppins({
  weight: "800",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chatbot FURIA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProviderWrapper>
      <html lang="en">
        <body className={poppins.className}>
          {children}
        </body>
      </html>
    </SessionProviderWrapper>
  );
}
